[build]
  base = "."
  command = "npm run build -w @holmeta/web"
  publish = "apps/web/.next"
  functions = "apps/web/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["apps/web/prisma/schema.prisma", "node_modules/.prisma/client/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
